host: "192.168.1.1"
username: "admin"
password: "password"
interface: "GigabitEthernet0/1"
ip_address: "192.168.1.100"
subnet_mask: "255.255.255.0"
commands:
  - "show version"
  - "show running-config"
