interface: "GigabitEthernet0/1"
ip_address: "192.168.1.100"
subnet_mask: "255.255.255.0"
commands:
  - "show version"
  - "show running-config"
  - "configure terminal"
  - "ip access-list standard ALLOW_ALL"
  - "permit 192.168.1.0 0.0.0.255"